#!/bin/bash
#
# Pre-commit hook to generate .css files from the .scss

# The main file we need to compile
MAIN=speeches

# Make sure that the 'compass' command exists (see http://stackoverflow.com/a/677212/329911)
command -v compass >/dev/null 2>&1 || {
  echo >&2 "Compass does not appear to be available. Unable to re-compile stylesheets"
  exit 1
}

dir_sass=""
for in in $( git diff-index --cached --name-only HEAD )
do
  if [[ $in == *.scss ]]; then
    dir_sass=$(dirname "$in")
  fi
done

if [ -n "$dir_sass" ]; then
    dir_static=$(dirname "$dir_sass")
    dir_css="$dir_static/css"
    mkdir -p "$dir_css"
    in="$dir_sass/$MAIN.scss"
    out="$dir_css/$MAIN.css"

    echo "Generating $out from $in"
    if ! compass compile --output-style=compressed -r zurb-foundation --sass-dir $dir_sass --css-dir $dir_css $in; then
      exit 1
    fi
    git add $out
fi

command -v flake8 >/dev/null 2>&1 || {
  echo >&2 "flake8 does not appear to be available. Unable to lint code."
  exit 1
}

flake8 && echo -e "\033[32mOK \033[0mflake8" || echo -e "\033[31mFAILED \033[0mflake8"
