#!/usr/bin/env python
#
# This is to wrap makemessages for including django-popolo strings in our
# translation file

import imp
import os
import sys
from shutil import rmtree

from django.conf import settings
from django.core.management import call_command

os.chdir(os.path.join(settings.PROJECT_ROOT, 'speeches'))

apps = ['popolo']

tempdir = 'extra-locales'

if os.path.exists(tempdir):
    if os.path.isdir(tempdir):
        rmtree(tempdir)
    else:
        sys.exit(
            "'extra-locales' exists and is not a directory. Please remove.")

os.mkdir(tempdir)

for app in apps:
    args = imp.find_module(app)
    mod = imp.load_module(app, *args)
    os.symlink(getattr(mod, '__path__')[0], os.path.join(tempdir, app))

call_command('makemessages', all=True, symlinks=True)

rmtree(tempdir)
