from speeches.tests.smoke_tests import *
from speeches.tests.speech_tests import *
from speeches.tests.selenium_tests import *
from speeches.tests.populate_speakers_command_tests import *
from speeches.tests.transcribe_task_tests import *
from speeches.tests.speech_api_tests import *
from speeches.tests.meeting_tests import *
from speeches.tests.debate_tests import *
from speeches.tests.speaker_tests import *
