import re

from .models import LoginToken, generate_token, NUMBER_OF_TOKEN_WORDS

from django.test import TestCase

class LoginTokenTests(TestCase):

    def test_login_token_creation(self):

        # This just checks that generate_token works at all:

        token = generate_token()
        words_in_token = token.split(' ')
        self.assertTrue(len(words_in_token) == NUMBER_OF_TOKEN_WORDS)

        for word in words_in_token:
            message = "An invalid word was generated by generate_token: %s"
            self.assertTrue(re.search('^[a-z]{4,}$', word),
                            message % (word,))

    def test_login_token_views(self):
        # FIXME: complete
        pass
