import re

from .models import *

from django.test import TestCase

class LoginTokenTests(TestCase):

    def test_login_token_creation(self):

        # This just checks that generate_token works at all:

        token = LoginToken.generate_token()
        self.assertTrue(len(token) == LoginToken.NUMBER_OF_TOKEN_WORDS)

        for word in token:
            message = "An invalid word was generated by generate_token: %s"
            self.assertTrue(re.search('^[a-z]{4,}$', word),
                            message % (word,))

    def test_login_token_views(self):
        # FIXME: complete
        pass
