name_fixes = {
    # The boss man
    'COURT': 'LORD JUSTICE LEVESON',
    'THE CHAIRMAN': 'LORD JUSTICE LEVESON',
    'THE JUDGE': 'LORD JUSTICE LEVESON',
    'LORD LEVESON': 'LORD JUSTICE LEVESON',
    'THE TECHNICIAN': 'TECHNICIAN',
    # Hard to spell
    'MR PATRY HOSKINS': 'MS PATRY HOSKINS',
    'MRS PATRY HOSKINS': 'MS PATRY HOSKINS',
    'MS PATRY-HOSKINS': 'MS PATRY HOSKINS',
    'MS DECOULOUS': 'MS DECOULOS',
    'MS MICHAOLOS': 'MS MICHALOS',
    'MER SHERBORNE': 'MR SHERBORNE',
    'LORD HUNT OF WIRRELL': 'DAVID JAMES FLETCHER LORD HUNT OF WIRRAL',
    # Different name used in different places
    'MS YOUNG': 'MS ELIZABETH YOUNG',
    'PROFESSOR TASIOULAS': 'PROFESSOR JOHN TASIOULAS',
    'MS PICKLES': 'MS ANNE PICKLES',
    'MS NIXON': 'MS ROSIE NIXON',
    'MR MCLELLAN': 'MR JOHN MCLELLAN',
    'MR LYONS': 'MR DARRYN PAUL LYONS',
    'MRS LLEWELLYN': 'MRS CATHERINE ANN LLEWELLYN',
    'DR MOORE': 'DR MARTIN MOORE',
    'DR UNGER': 'DR STEVEN WILLIAM UNGER',
    'MR ADAM SMITH': 'MR ADAM JOHN SMITH',
    'MR CUNNINGHAM': 'MR MIKE CUNNINGHAM',
    'NEIL WALLIS': 'NEIL JOHN WALLIS',
    'MS STANISTREET': 'MS MICHELLE STANISTREET',
    'MR RUSBRIDGER': 'MR ALAN CHARLES RUSBRIDGER',
    'MR RUSSELL': 'MR JONATHAN RUSSELL',
    'MR JULIAN PIKE': 'MR JULIAN CHARLES PIKE',
    'MR DOMINIC MOHAN': 'MR DOMINIC JAMES MOHAN',
    'MR JAMES HARDING': 'MR JAMES PAUL HARDING',
    'MR PAUL DACRE': 'MR PAUL MICHAEL DACRE',
    'MR THOMAS GERALD CRONE': 'MR THOMAS GERALD CRONE',
    'MS BIRD': 'MS JOANNE DENISE BIRD',
    'PROFESSOR BARNETT': 'PROFESSOR STEVEN BARNETT',
    'MS SUSAN AKERS': 'DAC SUE AKERS',
}

def fix_name(name):
    name = name.upper()
    return name_fixes.get(name, name)
