name_fixes = {
    # Charles Taylor
    'THE ACCUSED': 'DANKPANNAH DR CHARLES GHANKAY TAYLOR',
    'THE APPELLANT': 'DANKPANNAH DR CHARLES GHANKAY TAYLOR',
    'MR TAYLOR': 'DANKPANNAH DR CHARLES GHANKAY TAYLOR',

    # Judges
    'JUDGE DOHERTY': 'TERESA DOHERTY',
    'JUSTICE DOHERTY': 'TERESA DOHERTY',
    'JUDGE LUSSICK': 'RICHARD LUSSICK',
    'JUSTICE LUSSICK': 'RICHARD LUSSICK',
    'JUDGE SEBUTINDE': 'JULIA SEBUTINDE',
    'JUSTICE SEBUTINDE': 'JULIA SEBUTINDE',

    'PRESIDING JUGE': 'PRESIDING JUDGE',
    'PRESIDNG JUDGE': 'PRESIDING JUDGE',
    'THE PRESIDING JUDGE': 'PRESIDING JUDGE',
    'HER HONOUR': 'PRESIDING JUDGE',
    'MADAM PRESIDENT': 'PRESIDING JUDGE',
    'MR PRESIDENT': 'PRESIDING JUDGE',

    # Misspellings
    'MR GRIFFTITHS': 'MR GRIFFITHS',
    'GRIFFITHS': 'MR GRIFFITHS',

    'ANYAH': 'MR ANYAH',
    'MR ANYA': 'MR ANYAH',

    'MY KOUMJIAN': 'MR KOUMJIAN',
    'KOUMJIAN': 'MR KOUMJIAN',

    'MS MUZIGO': 'MS MUZIGO-MORRISON',

    'INTERPRETER': 'THE INTERPRETER',
    'MR INTERPRETER': 'THE INTERPRETER',
    'THE INTERPRETERS': 'THE INTERPRETER',

    # Alternate names
    'AUGUSTINE S MALLAH': 'AUGUSTINE SAMA MALLAH',
    'STEPHEN WILLIAM SMITH': 'STEPHEN SMITH',
    'MOHAMED BERETEH KABBAH': 'MOHAMED KABBAH',
}

def fix_name(name):
    name = name.upper()
    return name_fixes.get(name, name)
